sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
#  aws:
#    accessKeyId:
#    secretKey:
#    region:
#    s3:
#      bucketName:
  redis:
    host: localhost
    port: 6379
    database: 0
#  wechat:
#    appid:
#    secret: